# Generated by Django 3.2.23 on 2024-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_options',
            name='option_category',
            field=models.CharField(blank=True, choices=[('size', 'size'), ('colour', 'colour')], max_length=200),
        ),
    ]
