# Generated by Django 4.2.7 on 2024-02-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_gallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
