# Generated by Django 3.2.23 on 2024-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_option_category'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.Product_options'),
        ),
    ]
