# Generated by Django 4.2.7 on 2024-02-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
